"""A citation kind is coloured by a token, so it follows the theme.

Five kinds share one card, and each colours its icon differently so the
reader can tell a paper from a release before reading the title. Four of
them read a theme token. `paper` read the literal `#4338ca`, which is
`--series-3`'s LIGHT value — so on a dark page the one kind a research
document uses most kept the light palette while its four siblings
inverted, at 2.05:1 against its own icon plate. The inline underline
under the cited words had the same literal.

The card is measured from `data-def` — the exact markup the tooltip
shows, generated by `__okuBuildCitationBody` from the registry entry —
mounted inside a real `.oku-tooltip` so the icon plate composites over
the same surface it does in the tooltip. One kind is also measured by
hovering, which is the check that the two agree: without it this file
would be asserting about markup no reader ever sees.
"""

from __future__ import annotations

import http.server
import json
import re
import threading
from pathlib import Path

import pytest

from oku import cli
from oku_tests.browser._colour import composite, contrast

pytestmark = pytest.mark.browser

KIT = Path(__file__).resolve().parents[3] / "kit"

# One entry per icon kind. `paper` and `blog` declare `type`; the other
# three are inferred from the link, which is the route most registry
# entries take — so a change to `__okuCiteType` fails here too.
ENTRIES = {
    "Probe Paper": {"type": "paper", "link": "https://example.org/paper.pdf"},
    "Probe RFC": {"link": "https://datatracker.ietf.org/doc/html/rfc9457"},
    "Probe Release": {"link": "https://github.com/apache/iceberg/releases/tag/v1.4.0"},
    "Probe Blog": {"type": "blog", "link": "https://example.dev/notes"},
    "Probe Other": {"link": "https://example.com/thing"},
}
KINDS = ["paper", "rfc", "release", "blog", "other"]

KIT_JSON = {
    "name": "probe",
    "domains": ["probe"],
    "extrefs": {
        "probe": {
            name: {"en": dict(body, name=name, summary=f"A {name} entry.")} for name, body in ENTRIES.items()
        }
    },
}

PAGE = (
    "---\ntitle: Citations\nsummary: One citation of every kind.\n---\n\n"
    "## Cited {#cited}\n\nProse citing " + ", ".join(f"[{n}](#x/{n})" for n in ENTRIES) + ".\n"
)

READ = """(theme) => {
  document.documentElement.setAttribute('data-theme', theme);
  const host = document.createElement('div');
  host.className = 'oku-tooltip';
  host.style.cssText = 'position:absolute;left:-4000px;top:0';
  document.body.appendChild(host);
  // The plate is translucent, so what it composites over decides
  // whether the glyph reads. That is the tooltip's own surface, not the
  // page background — `document.body` is transparent here, which made an
  // earlier version of this file composite both themes over white and
  // report the dark page as safe.
  const out = { surface: getComputedStyle(host).backgroundColor, kinds: {} };
  for (const el of document.querySelectorAll('.oku-extref')) {
    const kind = el.getAttribute('data-cite-type');
    host.innerHTML = el.getAttribute('data-def') || '';
    const icon = host.querySelector('.okt-cite-icon');
    const card = host.querySelector('.okt-cite');
    out.kinds[kind] = {
      underline: getComputedStyle(el).borderBottomColor,
      glyph: icon ? getComputedStyle(icon).color : null,
      plate: icon ? getComputedStyle(icon).backgroundColor : null,
      built: !!card,
    };
  }
  host.remove();
  return out;
}"""


@pytest.fixture(scope="module")
def served(tmp_path_factory):
    d = tmp_path_factory.mktemp("citecolour").resolve()
    (d / "_oku").symlink_to(KIT, target_is_directory=True)
    (d / "kit.json").write_text(json.dumps(KIT_JSON), encoding="utf-8")
    (d / "page.md").write_text(PAGE, encoding="utf-8")
    (d / "page.html").write_text(
        cli._stub_for("page", inline_manifest={"schema_version": 1, "root": ".", "pages": []}),
        encoding="utf-8",
    )
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", 0), cli._make_serve_handler(d))
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    yield f"http://127.0.0.1:{httpd.server_address[1]}"
    httpd.shutdown()


@pytest.fixture(scope="module")
def measured(browser, served):
    pg = browser.new_page(viewport={"width": 1440, "height": 900})
    try:
        pg.goto(f"{served}/page.html")
        pg.wait_for_function("() => window.__okuRendered === true", timeout=60000)
        pg.wait_for_selector('.oku-extref[data-cite-type="paper"]', timeout=30000)
        light = pg.evaluate(READ, "light")
        dark = pg.evaluate(READ, "dark")

        # The live path, once: hover the paper citation and read the
        # tooltip's own icon rather than a remounted copy.
        pg.evaluate("() => document.documentElement.setAttribute('data-theme', 'dark')")
        el = pg.query_selector('.oku-extref[data-cite-type="paper"]')
        box = el.bounding_box()
        pg.mouse.move(box["x"] + box["width"] / 2, box["y"] + box["height"] / 2)
        pg.wait_for_selector(".oku-tooltip .okt-cite-icon", timeout=15000)
        hovered = pg.evaluate("""() => {
          const icon = document.querySelector('.oku-tooltip .okt-cite-icon');
          const card = document.querySelector('.oku-tooltip .okt-cite');
          return {
            type: card ? card.getAttribute('data-cite-type') : null,
            glyph: getComputedStyle(icon).color,
            plate: getComputedStyle(icon).backgroundColor,
          };
        }""")
        return {"light": light, "dark": dark, "hovered": hovered}
    finally:
        pg.close()


def test_every_kind_was_actually_rendered(measured) -> None:
    """The guard against a green run over an empty page: every assertion
    below is trivially true for a kind that never appeared."""
    for theme in ("light", "dark"):
        assert sorted(measured[theme]["kinds"]) == sorted(KINDS), measured[theme]["kinds"]
        for kind, v in measured[theme]["kinds"].items():
            assert v["glyph"], f"{theme}/{kind} built no card"


def test_no_citation_kind_keeps_its_colour_when_the_theme_flips(measured) -> None:
    """The defect itself. `paper` was identical in both themes; the
    other four inverted, which is what made it look deliberate."""
    frozen = [
        k
        for k in KINDS
        if measured["light"]["kinds"][k]["glyph"] == measured["dark"]["kinds"][k]["glyph"]
        or measured["light"]["kinds"][k]["underline"] == measured["dark"]["kinds"][k]["underline"]
    ]
    assert frozen == [], f"{frozen} paint the same colour on a light and a dark page"


def test_the_two_themes_were_really_two_themes(measured) -> None:
    """The contrast test below composites over the card surface, so a
    theme flip that silently did nothing would report the light figures
    twice and pass."""
    assert measured["light"]["surface"] != measured["dark"]["surface"], measured["light"]["surface"]


def test_every_kind_reads_against_its_own_icon_plate(measured) -> None:
    """WCAG 1.4.11 puts a graphical object at 3:1. Measured before the
    fix: paper 2.05:1 on dark, against 8.7 to 14.8 for the other four."""
    worst = {}
    for theme in ("light", "dark"):
        for kind, v in measured[theme]["kinds"].items():
            plate = composite(v["plate"], measured[theme]["surface"])
            worst[f"{theme}/{kind}"] = round(contrast(v["glyph"], plate), 2)
    failing = {k: r for k, r in worst.items() if r < 3.0}
    assert failing == {}, f"{failing} — all: {worst}"


def test_the_underline_and_the_icon_agree_on_the_kind(measured) -> None:
    """One decision, two surfaces: the words in the prose and the icon
    in the card. They were set by two different rules, which is how one
    of them drifted."""
    for theme in ("light", "dark"):
        v = measured[theme]["kinds"]["paper"]
        assert v["underline"] == v["glyph"], (
            f"{theme}: {v['underline']} under the words, {v['glyph']} in the card"
        )


def test_the_hovered_card_matches_the_measured_markup(measured) -> None:
    assert measured["hovered"]["type"] == "paper"
    assert measured["hovered"]["glyph"] == measured["dark"]["kinds"]["paper"]["glyph"]
    assert measured["hovered"]["plate"] == measured["dark"]["kinds"]["paper"]["plate"]


def test_no_citation_rule_carries_a_raw_colour() -> None:
    """The class, not the instance: any of the five could be written as
    a literal, and a literal is invisible until someone opens the page
    in the theme it was not written for."""
    css = (KIT / "chrome.css").read_text(encoding="utf-8")
    literal = re.compile(r"#[0-9a-fA-F]{3,8}\b|\brgba?\(")
    offenders = [
        line.strip()
        for line in css.splitlines()
        if "data-cite-type" in line.split("/*")[0] and literal.search(line.split("{", 1)[-1])
    ]
    assert offenders == [], offenders
